apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ${SECRET_STORE_NAME}
    kind: ${SECRET_STORE_KIND}
  target:
    name: ${SERVICE_NAME}-config
    creationPolicy: Owner
    template:
      type: Opaque
  data:
${EXTERNAL_SECRET_DATA}