apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
  namespace: digitalaurion-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-service
  template:
    metadata:
      labels:
        app: python-service
    spec:
      containers:
        - name: python-service
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/python-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: digitalaurion-test
spec:
  selector:
    app: python-service
  ports:
    - port: 80
      targetPort: 8000
