apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
  namespace: ai.digitalaurion.aurion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-service
  template:
    metadata:
      labels:
        app: python-service
    spec:
      containers:
        - name: python-service
          image: python-service:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: ai.digitalaurion.aurion
spec:
  selector:
    app: python-service
  ports:
    - port: 80
      targetPort: 8000
