name: Deploy to EKS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::<your-account-id>:role/<your-github-role>
          aws-region: ap-southeast-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/00-namespace.yaml
          kubectl apply -f k8s/go-deployment.yaml
          kubectl apply -f k8s/python-deployment.yaml
          kubectl apply -f k8s/ingress.yaml
