name: Deploy to EKS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::440744252731:role/<your-github-role>
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Python service Docker image
        run: |
          docker build -t python-service ./python-service
          docker tag python-service:latest 440744252731.dkr.ecr.ap-southeast-1.amazonaws.com/python-service:latest
          docker push 440744252731.dkr.ecr.ap-southeast-1.amazonaws.com/python-service:latest

      - name: Build and push Go service Docker image
        run: |
          docker build -t go-service ./go-service
          docker tag go-service:latest 440744252731.dkr.ecr.ap-southeast-1.amazonaws.com/go-service:latest
          docker push 440744252731.dkr.ecr.ap-southeast-1.amazonaws.com/go-service:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/00-namespace.yaml
          kubectl apply -f k8s/go-deployment.yaml
          kubectl apply -f k8s/python-deployment.yaml
          kubectl apply -f k8s/ingress.yaml
