# This workflow will build and deploy a Python and Go application to EKS

# Required secrets to be added in GitHub repository Settings → Secrets and variables → Actions:
#
# Name                   Description
# AWS_ACCOUNT_ID         Your AWS Account ID
# AWS_REGION             Your AWS Region
# AWS_GITHUB_ROLE_ARN    GitHub OIDC Role ARN output from terraform apply
#
# Example:
#   AWS_ACCOUNT_ID=123456789012
#   AWS_REGION=ap-southeast-1
#   AWS_GITHUB_ROLE_ARN=arn:aws:iam::123456789012:role/aurion-github-actions-role
#
# Usage:
# Push changes to main branch, GitHub Actions will automatically:
#   - Login to ECR
#   - Build and push images
#   - Deploy to EKS
# You can also manually trigger via "Run workflow" in GitHub Web interface.

name: Build & Deploy via Makefile

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      run: make login-ecr

    - name: Build & Push Python Image
      run: make push-python

    - name: Build & Push Go Image
      run: make push-go

    - name: Deploy to EKS
      run: make deploy
